# Generated by Django 2.1.3 on 2020-06-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_binding',
            field=models.BooleanField(default=False, verbose_name='是否绑定'),
        ),
    ]
