# Generated by Django 2.1.3 on 2020-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'doc'), (2, 'docx'), (3, 'csv'), (4, 'txt'), (5, 'text')], default=1, verbose_name='文件类型'),
        ),
    ]
