# Generated by Django 2.1.8 on 2020-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_storage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='process_method',
            field=models.SmallIntegerField(choices=[(1, 'kenlm'), (2, '百度api')], default=1, verbose_name='处理方式'),
        ),
        migrations.AlterField(
            model_name='document',
            name='success_url',
            field=models.CharField(default='', max_length=3072, verbose_name='纠错完成文件存储位置'),
        ),
    ]
